<a href="https://colab.research.google.com/github/springboardmentor425/MediAlert-AI-Anomaly-Detection-for-Smarter-Healthcare-Insights/blob/main/Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Load dataset
df = pd.read_csv('/content/Healthcare Providers.csv')

# Inspect the first few rows to understand the data
df.head()

,index,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,...,HCPCS Code,HCPCS Description,HCPCS Drug Indicator,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount
0,8774979,1891106191,UPADHYAYULA,SATYASREE,NaN,M.D.,F,I,1402 S GRAND BLVD,FDT 14TH FLOOR,...,99223,"Initial hospital inpatient care, typically 70 ...",N,27,24,27,200.5877778,305.2111111,157.2622222,160.9088889
1,3354385,1346202256,JONES,WENDY,P,M.D.,F,I,2950 VILLAGE DR,NaN,...,G0202,"Screening mammography, bilateral (2-view study...",N,175,175,175,123.73,548.8,118.83,135.3152571
2,3001884,1306820956,DUROCHER,RICHARD,W,DPM,M,I,20 WASHINGTON AVE,STE 212,...,99348,"Established patient home visit, typically 25 m...",N,32,13,32,90.65,155,64.4396875,60.5959375
3,7594822,1770523540,FULLARD,JASPER,NaN,MD,M,I,5746 N BROADWAY ST,NaN,...,81002,"Urinalysis, manual test",N,20,18,20,3.5,5,3.43,3.43
4,746159,1073627758,PERROTTI,ANTHONY,E,DO,M,I,875 MILITARY TRL,SUITE 200,...,96372,Injection beneath the skin or into muscle for ...,N,33,24,31,26.52,40,19.53939394,19.05757576

In [2]:
missing_values = df.isnull().sum()
print(missing_values)

index                                                          0
National Provider Identifier                                   0
Last Name/Organization Name of the Provider                    1
First Name of the Provider                                   213
Middle Initial of the Provider                              1351
Credentials of the Provider                                  346
Gender of the Provider                                       213
Entity Type of the Provider                                    1
Street Address 1 of the Provider                               1
Street Address 2 of the Provider                            2707
City of the Provider                                           1
Zip Code of the Provider                                       1
State Code of the Provider                                     1
Country Code of the Provider                                   1
Provider Type                                                  1
Medicare Participation Indicator                               1
Place of Service                                               1
HCPCS Code                                                     1
HCPCS Description                                              1
HCPCS Drug Indicator                                           1
Number of Services                                             1
Number of Medicare Beneficiaries                               1
Number of Distinct Medicare Beneficiary/Per Day Services       1
Average Medicare Allowed Amount                                1
Average Submitted Charge Amount                                1
Average Medicare Payment Amount                                1
Average Medicare Standardized Amount                           1
dtype: int64

In [3]:
# Drop rows with missing values
df = df.dropna()

# Drop columns with more than 30% missing values
df = df.dropna(thresh=int(0.7*len(df)), axis=1)
print(df)

        index  National Provider Identifier  \
2     3001884                    1306820956
4      746159                    1073627758
7     6169160                    1629160551
16    3642669                    1366846719
17    7008969                    1710088190
...       ...                           ...
4488  7370757                    1740488238
4490  7080550                    1710973433
4498  1109350                    1114184389
4501  3185724                    1326048653
4502   813964                    1083646368

     Last Name/Organization Name of the Provider First Name of the Provider  \
2                                       DUROCHER                    RICHARD
4                                       PERROTTI                    ANTHONY
7                                      GALBREATH                     RONALD
16                                        ORREGO                      MARIA
17                                      CAMPBELL                      AARON
...                                          ...                        ...
4488                                     SIMPSON                    GREGORY
4490                                        HAAS                     ROBERT
4498                                      KEPLER                CHRISTOPHER
4501                                       RUBIN                        HAL
4502                                       CROSS                   PATRICIA

     Middle Initial of the Provider Credentials of the Provider  \
2                                 W                         DPM
4                                 E                          DO
7                                 G                        M.D.
16                                X                        PA-C
17                                W                         M.D
...                             ...                         ...
4488                              L                        M.D.
4490                              J                          MD
4498                              K                        M.D.
4501                              I                          MD
4502                              A                          MD

     Gender of the Provider Entity Type of the Provider  \
2                         M                           I
4                         M                           I
7                         M                           I
16                        F                           I
17                        M                           I
...                     ...                         ...
4488                      M                           I
4490                      M                           I
4498                      M                           I
4501                      M                           I
4502                      F                           I

     Street Address 1 of the Provider Street Address 2 of the Provider  ...  \
2                   20 WASHINGTON AVE                          STE 212  ...
4                    875 MILITARY TRL                        SUITE 200  ...
7               12522 E. LAMBERT ROAD                          SUITE D  ...
16                1801 INWOOD RD FL 7                        SUITE 120  ...
17                 605 MEDICAL COURTS                        SUITE 203  ...
...                               ...                              ...  ...
4488                2335 E KASHIAN LN                        SUITE 410  ...
4490                 7444 W ALASKA DR                          STE 250  ...
4498                  925 CHESTNUT ST                      FIFTH FLOOR  ...
4501                    11 HAMMOND LN                          SUITE A  ...
4502                    200 GROTON RD             RADIOLOGY DEPARTMENT  ...

     HCPCS Code                                  HCPCS Description  \
2         99348  Established patient home visit, typically 25 m...
4         96372  Injection beneath the skin or into muscle for ...
7         G0008          Administration of influenza virus vaccine
16        99213  Established patient office or other outpatient...
17        99212  Established patient office or other outpatient...
...         ...                                                ...
4488      99202  New patient office or other outpatient visit, ...
4490      88312  Special stained specimen slides to identify or...
4498      22600  Fusion of upper spine bones, posterior or post...
4501      90838                          Psychotherapy, 60 minutes
4502      74176                      CT scan of abdomen and pelvis

     HCPCS Drug Indicator Number of Services Number of Medicare Beneficiaries  \
2                       N                 32                               13
4                       N                 33                               24
7                       N                 52                               50
16                      N                364                              300
17                      N                 21                               14
...                   ...                ...                              ...
4488                    N                 53                               53
4490                    N                 38                               30
4498                    N                 28                               28
4501                    N                 14                               11
4502                    N                 64                               62

     Number of Distinct Medicare Beneficiary/Per Day Services  \
2                                                    32
4                                                    31
7                                                    52
16                                                  364
17                                                   21
...                                                 ...
4488                                                 53
4490                                                 30
4498                                                 28
4501                                                 14
4502                                                 64

     Average Medicare Allowed Amount Average Submitted Charge Amount  \
2                              90.65                             155
4                              26.52                              40
7                              29.33                              50
16                             63.16                     193.5604396
17                             42.06                     87.66666667
...                              ...                             ...
4488                           78.53                             164
4490                            28.5                              50
4498                        880.2125                           6,500
4501                           105.8                             170
4502                      90.3290625                       251.71875

     Average Medicare Payment Amount Average Medicare Standardized Amount
2                         64.4396875                           60.5959375
4                        19.53939394                          19.05757576
7                              28.74                                25.32
16                       40.64532967                          41.17607143
17                       26.69809524                          28.40619048
...                              ...                                  ...
4488                     50.42830189                          49.69584906
4490                     21.75394737                          22.37631579
4498                     690.0839286                          614.8664286
4501                          77.025                          81.37214286
4502                           54.84                          53.14859375

[1296 rows x 27 columns]

In [4]:
# Identify numerical columns
numerical_columns = df.select_dtypes(include=['number']).columns
print("Numerical columns:", numerical_columns)

Numerical columns: Index(['index', 'National Provider Identifier', 'Zip Code of the Provider'], dtype='object')

In [5]:
# identify categorical columns
categorical_cols = df.select_dtypes(include=['object','category']).columns
print(categorical_cols)

Index(['Last Name/Organization Name of the Provider',
       'First Name of the Provider', 'Middle Initial of the Provider',
       'Credentials of the Provider', 'Gender of the Provider',
       'Entity Type of the Provider', 'Street Address 1 of the Provider',
       'Street Address 2 of the Provider', 'City of the Provider',
       'State Code of the Provider', 'Country Code of the Provider',
       'Provider Type', 'Medicare Participation Indicator', 'Place of Service',
       'HCPCS Code', 'HCPCS Description', 'HCPCS Drug Indicator',
       'Number of Services', 'Number of Medicare Beneficiaries',
       'Number of Distinct Medicare Beneficiary/Per Day Services',
       'Average Medicare Allowed Amount', 'Average Submitted Charge Amount',
       'Average Medicare Payment Amount',
       'Average Medicare Standardized Amount'],
      dtype='object')

In [6]:
#Preprocessing Based on Column Type
# Nominal Columns (No ordering, like "Gender", "Country")
categorical_cols_nominal = ['Gender of the Provider', 'City of the Provider']  # Define nominal columns
df_nominal = pd.get_dummies(df[categorical_cols_nominal], drop_first=True)
print(df_nominal)

      Gender of the Provider_M  City of the Provider_AKRON  \
2                         True                       False
4                         True                       False
7                         True                       False
16                       False                       False
17                        True                       False
...                        ...                         ...
4488                      True                       False
4490                      True                       False
4498                      True                       False
4501                      True                       False
4502                     False                       False

      City of the Provider_ALBANY  City of the Provider_ALBUQUERQUE  \
2                           False                             False
4                           False                             False
7                           False                             False
16                          False                             False
17                          False                             False
...                           ...                               ...
4488                        False                             False
4490                        False                             False
4498                        False                             False
4501                        False                             False
4502                        False                             False

      City of the Provider_ALEXANDRIA  City of the Provider_ALLENTOWN  \
2                               False                           False
4                               False                           False
7                               False                           False
16                              False                           False
17                              False                           False
...                               ...                             ...
4488                            False                           False
4490                            False                           False
4498                            False                           False
4501                            False                           False
4502                            False                           False

      City of the Provider_ALTAMONTE SPRINGS  City of the Provider_ALTON  \
2                                      False                       False
4                                      False                       False
7                                      False                       False
16                                     False                       False
17                                     False                       False
...                                      ...                         ...
4488                                   False                       False
4490                                   False                       False
4498                                   False                       False
4501                                   False                       False
4502                                   False                       False

      City of the Provider_AMARILLO  City of the Provider_AMES  ...  \
2                             False                      False  ...
4                             False                      False  ...
7                             False                      False  ...
16                            False                      False  ...
17                            False                      False  ...
...                             ...                        ...  ...
4488                          False                      False  ...
4490                          False                      False  ...
4498                          False                      False  ...
4501                          False                      False  ...
4502                          False                      False  ...

      City of the Provider_WOODSTOCK  City of the Provider_WOONSOCKET  \
2                              False                            False
4                              False                            False
7                              False                            False
16                             False                            False
17                             False                            False
...                              ...                              ...
4488                           False                            False
4490                           False                            False
4498                           False                            False
4501                           False                            False
4502                           False                            False

      City of the Provider_WORCESTER  City of the Provider_WYNNEWOOD  \
2                              False                           False
4                              False                           False
7                              False                           False
16                             False                           False
17                             False                           False
...                              ...                             ...
4488                           False                           False
4490                           False                           False
4498                           False                           False
4501                           False                           False
4502                           False                           False

      City of the Provider_WYOMING  City of the Provider_YAKIMA  \
2                            False                        False
4                            False                        False
7                            False                        False
16                           False                        False
17                           False                        False
...                            ...                          ...
4488                         False                        False
4490                         False                        False
4498                         False                        False
4501                         False                        False
4502                         False                        False

      City of the Provider_YOUNGSTOWN  City of the Provider_YPSILANTI  \
2                               False                           False
4                               False                           False
7                               False                           False
16                              False                           False
17                              False                           False
...                               ...                             ...
4488                            False                           False
4490                            False                           False
4498                            False                           False
4501                            False                           False
4502                            False                           False

      City of the Provider_YUCCA VALLEY  City of the Provider_ZACHARY
2                                 False                         False
4                                 False                         False
7                                 False                         False
16                                False                         False
17                                False                         False
...                                 ...                           ...
4488                              False                         False
4490                              False                         False
4498                              False                         False
4501                              False                         False
4502                              False                         False

[1296 rows x 690 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder instance
le = LabelEncoder()

# List of categorical columns to encode
categorical_cols_to_encode = ['Last Name/Organization Name of the Provider',
       'First Name of the Provider', 'Middle Initial of the Provider',
       'Credentials of the Provider', 'Gender of the Provider',
       'Entity Type of the Provider', 'Street Address 1 of the Provider',
       'Street Address 2 of the Provider', 'City of the Provider',
       'State Code of the Provider', 'Country Code of the Provider',
       'Provider Type', 'Medicare Participation Indicator', 'Place of Service',
       'HCPCS Code', 'HCPCS Description', 'HCPCS Drug Indicator',
       'Number of Services', 'Number of Medicare Beneficiaries',
       'Number of Distinct Medicare Beneficiary/Per Day Services',
       'Average Medicare Allowed Amount', 'Average Submitted Charge Amount',
       'Average Medicare Payment Amount',
       'Average Medicare Standardized Amount']

# Loop through each categorical column and apply Label Encoding
for col in categorical_cols_to_encode:
    df[col] = le.fit_transform(df[col])

In [8]:
#Ordinal Columns (Ordered categories, like "Education Level")
from sklearn.preprocessing import OrdinalEncoder

# Define ordinal columns
categorical_cols_ordinal = ['Number of Medicare Beneficiaries', 'Number of Distinct Medicare Beneficiary/Per Day Services']

ordinal_encoder = OrdinalEncoder()
df_ordinal = df[categorical_cols_ordinal].copy()

# Apply ordinal encoding
df_ordinal[categorical_cols_ordinal] = ordinal_encoder.fit_transform(df_ordinal[categorical_cols_ordinal])
print(df_ordinal)

      Number of Medicare Beneficiaries  \
2                                 31.0
4                                110.0
7                                194.0
16                               139.0
17                                41.0
...                                ...
4488                             202.0
4490                             138.0
4498                             132.0
4501                              12.0
4502                             221.0

      Number of Distinct Medicare Beneficiary/Per Day Services
2                                                 170.0
4                                                 167.0
7                                                 248.0
16                                                197.0
17                                                109.0
...                                                 ...
4488                                              250.0
4490                                              163.0
4498                                              152.0
4501                                               50.0
4502                                              276.0

[1296 rows x 2 columns]

In [10]:
from sklearn.preprocessing import MinMaxScaler

# Create a MinMaxScaler instance
scaler = MinMaxScaler()

# Fit and transform the selected columns and store the result in separate columns
df[['National Provider Identifier_scaled', 'Zip Code of the Provider_scaled']] = scaler.fit_transform(df[['National Provider Identifier', 'Zip Code of the Provider']])

# If you need a single 'numerical_column', you can create it based on the scaled columns:
# For example, you could average the scaled values:
# df['numerical_column'] = (df['National Provider Identifier_scaled'] + df['Zip Code of the Provider_scaled']) / 2

# Or you could choose one of the scaled columns as the 'numerical_column':
# df['numerical_column'] = df['National Provider Identifier_scaled']

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['numerical_column1', 'numerical_column2']] = scaler.fit_transform(df[['National Provider Identifier','Zip Code of the Provider']])

In [14]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.6.4-py2.py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.26.4)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.6.0)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.13.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.4)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2024.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.6.4-py2.py3-none-any.whl (82 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.0/82.0 kB 2.0 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.6.4

In [15]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder
import category_encoders as ce

# Load the dataset
df = pd.read_csv('/content/Healthcare Providers.csv')

# 1. Create 'numerical_column' and fill with 'National Provider Identifier' values
df['numerical_column'] = df['National Provider Identifier']

# Handle missing values (example for numerical and categorical columns)
# 2. Now you can fill NaN values in 'numerical_column' using its median
df['numerical_column'] = df['numerical_column'].fillna(df['numerical_column'].median())

# Create 'categorical_column' and fill it with 'Gender of the Provider' values
df['categorical_column'] = df['Gender of the Provider']

# 3. Now you can fill NaN values in 'categorical_column' using its mode
df['categorical_column'] = df['categorical_column'].fillna(df['categorical_column'].mode()[0])

# Encode categorical columns using One-Hot Encoding or Label Encoding
df = pd.get_dummies(df, columns=['categorical_column'])  # One-Hot Encoding
# Alternatively, use Label Encoding for ordinal features
# le = LabelEncoder()
# df['category_column'] = le.fit_transform(df['category_column'])

# Normalize or Standardize numerical columns
scaler = StandardScaler()
df['numerical_column'] = scaler.fit_transform(df[['numerical_column']])

# Alternatively, for Min-Max normalization:
# scaler = MinMaxScaler()
# df['numerical_column'] = scaler.fit_transform(df[['numerical_column']])

# Print the cleaned dataframe
print(df.head())

     index  National Provider Identifier  \
0  8774979                    1891106191
1  3354385                    1346202256
2  3001884                    1306820956
3  7594822                    1770523540
4   746159                    1073627758

  Last Name/Organization Name of the Provider First Name of the Provider  \
0                                 UPADHYAYULA                  SATYASREE
1                                       JONES                      WENDY
2                                    DUROCHER                    RICHARD
3                                     FULLARD                     JASPER
4                                    PERROTTI                    ANTHONY

  Middle Initial of the Provider Credentials of the Provider  \
0                            NaN                        M.D.
1                              P                        M.D.
2                              W                         DPM
3                            NaN                          MD
4                              E                          DO

  Gender of the Provider Entity Type of the Provider  \
0                      F                           I
1                      F                           I
2                      M                           I
3                      M                           I
4                      M                           I

  Street Address 1 of the Provider Street Address 2 of the Provider  ...  \
0                1402 S GRAND BLVD                   FDT 14TH FLOOR  ...
1                  2950 VILLAGE DR                              NaN  ...
2                20 WASHINGTON AVE                          STE 212  ...
3               5746 N BROADWAY ST                              NaN  ...
4                 875 MILITARY TRL                        SUITE 200  ...

  Number of Services  Number of Medicare Beneficiaries  \
0                 27                                24
1                175                               175
2                 32                                13
3                 20                                18
4                 33                                24

  Number of Distinct Medicare Beneficiary/Per Day Services  \
0                                                 27
1                                                175
2                                                 32
3                                                 20
4                                                 31

  Average Medicare Allowed Amount Average Submitted Charge Amount  \
0                     200.5877778                     305.2111111
1                          123.73                           548.8
2                           90.65                             155
3                             3.5                               5
4                           26.52                              40

  Average Medicare Payment Amount Average Medicare Standardized Amount  \
0                     157.2622222                          160.9088889
1                          118.83                          135.3152571
2                      64.4396875                           60.5959375
3                            3.43                                 3.43
4                     19.53939394                          19.05757576

  numerical_column categorical_column_F categorical_column_M
0         1.366960                 True                False
1        -0.528945                 True                False
2        -0.665966                False                 True
3         0.947412                False                 True
4        -1.477323                False                 True

[5 rows x 30 columns]

In [16]:
# Final dataset with all preprocessing applied
print("Preprocessing complete. Here is the updated dataset:")
print(df.head())

Preprocessing complete. Here is the updated dataset:
     index  National Provider Identifier  \
0  8774979                    1891106191
1  3354385                    1346202256
2  3001884                    1306820956
3  7594822                    1770523540
4   746159                    1073627758

  Last Name/Organization Name of the Provider First Name of the Provider  \
0                                 UPADHYAYULA                  SATYASREE
1                                       JONES                      WENDY
2                                    DUROCHER                    RICHARD
3                                     FULLARD                     JASPER
4                                    PERROTTI                    ANTHONY

  Middle Initial of the Provider Credentials of the Provider  \
0                            NaN                        M.D.
1                              P                        M.D.
2                              W                         DPM
3                            NaN                          MD
4                              E                          DO

  Gender of the Provider Entity Type of the Provider  \
0                      F                           I
1                      F                           I
2                      M                           I
3                      M                           I
4                      M                           I

  Street Address 1 of the Provider Street Address 2 of the Provider  ...  \
0                1402 S GRAND BLVD                   FDT 14TH FLOOR  ...
1                  2950 VILLAGE DR                              NaN  ...
2                20 WASHINGTON AVE                          STE 212  ...
3               5746 N BROADWAY ST                              NaN  ...
4                 875 MILITARY TRL                        SUITE 200  ...

  Number of Services  Number of Medicare Beneficiaries  \
0                 27                                24
1                175                               175
2                 32                                13
3                 20                                18
4                 33                                24

  Number of Distinct Medicare Beneficiary/Per Day Services  \
0                                                 27
1                                                175
2                                                 32
3                                                 20
4                                                 31

  Average Medicare Allowed Amount Average Submitted Charge Amount  \
0                     200.5877778                     305.2111111
1                          123.73                           548.8
2                           90.65                             155
3                             3.5                               5
4                           26.52                              40

  Average Medicare Payment Amount Average Medicare Standardized Amount  \
0                     157.2622222                          160.9088889
1                          118.83                          135.3152571
2                      64.4396875                           60.5959375
3                            3.43                                 3.43
4                     19.53939394                          19.05757576

  numerical_column categorical_column_F categorical_column_M
0         1.366960                 True                False
1        -0.528945                 True                False
2        -0.665966                False                 True
3         0.947412                False                 True
4        -1.477323                False                 True

[5 rows x 30 columns]