In [208]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [210]:
df = pd.read_csv("Healthcare Providers.csv")

In [211]:
df.head(10)

,index,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,...,HCPCS Code,HCPCS Description,HCPCS Drug Indicator,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount
0,8774979,1891106191,UPADHYAYULA,SATYASREE,NaN,M.D.,F,I,1402 S GRAND BLVD,FDT 14TH FLOOR,...,99223,"Initial hospital inpatient care, typically 70 ...",N,27,24,27,200.58777778,305.21111111,157.26222222,160.90888889
1,3354385,1346202256,JONES,WENDY,P,M.D.,F,I,2950 VILLAGE DR,NaN,...,G0202,"Screening mammography, bilateral (2-view study...",N,175,175,175,123.73,548.8,118.83,135.31525714
2,3001884,1306820956,DUROCHER,RICHARD,W,DPM,M,I,20 WASHINGTON AVE,STE 212,...,99348,"Established patient home visit, typically 25 m...",N,32,13,32,90.65,155,64.4396875,60.5959375
3,7594822,1770523540,FULLARD,JASPER,NaN,MD,M,I,5746 N BROADWAY ST,NaN,...,81002,"Urinalysis, manual test",N,20,18,20,3.5,5,3.43,3.43
4,746159,1073627758,PERROTTI,ANTHONY,E,DO,M,I,875 MILITARY TRL,SUITE 200,...,96372,Injection beneath the skin or into muscle for ...,N,33,24,31,26.52,40,19.539393939,19.057575758
5,3443985,1346571551,PUGH,JOHN,R,DPT,M,I,504 ALBEMARLE SQ,NaN,...,97016,Application of blood vessel compression or dec...,N,192,36,192,13.550989583,63.1125,9.6764583333,10.506927083
6,2137027,1215943535,BRUMITT,TOM,B,DO,M,I,70 DOCTORS PARK,NaN,...,20610,Aspiration and/or injection of large joint or ...,N,21,19,21,45.971904762,164.57142857,36.036190476,37.77952381
7,6169160,1629160551,GALBREATH,RONALD,G,M.D.,M,I,12522 E. LAMBERT ROAD,SUITE D,...,G0008,Administration of influenza virus vaccine,N,52,50,52,29.33,50,28.74,25.32
8,5086226,1518929124,BOONE,RALPH,M,D.O.,M,I,1215 DUNN AVE,NaN,...,80061,"Blood test, lipids (cholesterol and triglyceri...",N,73,68,73,15.510410959,76,15.197945205,15.197945205
9,3900718,1396781134,METWEST INC,NaN,NaN,NaN,NaN,O,695 S BROADWAY,NaN,...,84392,Urine sulfate (acid) level,N,19,16,19,6.51,29.65,6.38,6.38

In [214]:
df.shape

(100000, 27)

In [216]:
print("\nDataset information")
df.info()

Dataset information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   index                                                     100000 non-null  int64
 1   National Provider Identifier                              100000 non-null  int64
 2   Last Name/Organization Name of the Provider               100000 non-null  object
 3   First Name of the Provider                                95745 non-null   object
 4   Middle Initial of the Provider                            70669 non-null   object
 5   Credentials of the Provider                               92791 non-null   object
 6   Gender of the Provider                                    95746 non-null   object
 7   Entity Type of the Provider                               100000 non-null  object
 8   Street Address 1 of the Provider                          100000 non-null  object
 9   Street Address 2 of the Provider                          40637 non-null   object
 10  City of the Provider                                      100000 non-null  object
 11  Zip Code of the Provider                                  100000 non-null  float64
 12  State Code of the Provider                                100000 non-null  object
 13  Country Code of the Provider                              100000 non-null  object
 14  Provider Type                                             100000 non-null  object
 15  Medicare Participation Indicator                          100000 non-null  object
 16  Place of Service                                          100000 non-null  object
 17  HCPCS Code                                                100000 non-null  object
 18  HCPCS Description                                         100000 non-null  object
 19  HCPCS Drug Indicator                                      100000 non-null  object
 20  Number of Services                                        100000 non-null  object
 21  Number of Medicare Beneficiaries                          100000 non-null  object
 22  Number of Distinct Medicare Beneficiary/Per Day Services  100000 non-null  object
 23  Average Medicare Allowed Amount                           100000 non-null  object
 24  Average Submitted Charge Amount                           100000 non-null  object
 25  Average Medicare Payment Amount                           100000 non-null  object
 26  Average Medicare Standardized Amount                      100000 non-null  object
dtypes: float64(1), int64(2), object(24)
memory usage: 20.6+ MB

In [218]:
df.describe(include='all')

,index,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,...,HCPCS Code,HCPCS Description,HCPCS Drug Indicator,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount
count,1.000000e+05,1.000000e+05,100000,95745,70669,92791,95746,100000,100000,40637,...,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000
unique,NaN,NaN,42820,13022,29,1854,2,2,51928,10024,...,2631,2455,2,2748,1274,1979,49629,38088,83367,76237
top,NaN,NaN,PATEL,MICHAEL,A,MD,M,I,200 1ST ST SW,SUITE 200,...,99213,Established patient office or other outpatient...,N,13,11,12,3,150,2.94,25.32
freq,NaN,NaN,557,2350,8152,32874,66641,95746,244,1624,...,4578,4578,93802,3018,4791,3210,1017,970,623,1630
mean,4.907646e+06,1.498227e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2.839633e+06,2.874125e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2.090000e+02,1.003001e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2.458791e+06,1.245669e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,4.901266e+06,1.497847e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,7.349450e+06,1.740374e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,9.847440e+06,1.993000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [220]:
# Check for missing values in the dataset
missing_values = df.isnull().sum()

# Display columns with missing values and their counts
print("\nMissing Values in Each Column:")
print(missing_values[missing_values > 0])

# Display the total number of missing values
total_missing = missing_values.sum()
print(f"\nTotal Missing Values in the Dataset: {total_missing}")

Missing Values in Each Column:
First Name of the Provider           4255
Middle Initial of the Provider      29331
Credentials of the Provider          7209
Gender of the Provider               4254
Street Address 2 of the Provider    59363
dtype: int64

Total Missing Values in the Dataset: 104412

In [222]:
# Remove columns with more than 50% missing values
cleaned_df = df.dropna(thresh=len(df) * 0.5, axis=1)

In [224]:
# Display the shape of the DataFrame after removing such columns
print("Shape after removing columns with more than 50% missing values:")
print(cleaned_df.shape)

Shape after removing columns with more than 50% missing values:
(100000, 26)

In [226]:
# Optional: Check the columns that were retained
print("\nColumns retained:")
print(cleaned_df.columns)

Columns retained:
Index(['index', 'National Provider Identifier',
       'Last Name/Organization Name of the Provider',
       'First Name of the Provider', 'Middle Initial of the Provider',
       'Credentials of the Provider', 'Gender of the Provider',
       'Entity Type of the Provider', 'Street Address 1 of the Provider',
       'City of the Provider', 'Zip Code of the Provider',
       'State Code of the Provider', 'Country Code of the Provider',
       'Provider Type', 'Medicare Participation Indicator', 'Place of Service',
       'HCPCS Code', 'HCPCS Description', 'HCPCS Drug Indicator',
       'Number of Services', 'Number of Medicare Beneficiaries',
       'Number of Distinct Medicare Beneficiary/Per Day Services',
       'Average Medicare Allowed Amount', 'Average Submitted Charge Amount',
       'Average Medicare Payment Amount',
       'Average Medicare Standardized Amount'],
      dtype='object')

In [228]:
#Step 1: Fill missing values in categorical columns with the mode
cleaned_df[categorical_columns] = cleaned_df[categorical_columns].apply(lambda col: col.fillna(col.mode()[0]))

In [230]:
print(cleaned_df.isnull().sum())

index                                                       0
National Provider Identifier                                0
Last Name/Organization Name of the Provider                 0
First Name of the Provider                                  0
Middle Initial of the Provider                              0
Credentials of the Provider                                 0
Gender of the Provider                                      0
Entity Type of the Provider                                 0
Street Address 1 of the Provider                            0
City of the Provider                                        0
Zip Code of the Provider                                    0
State Code of the Provider                                  0
Country Code of the Provider                                0
Provider Type                                               0
Medicare Participation Indicator                            0
Place of Service                                            0
HCPCS Code                                                  0
HCPCS Description                                           0
HCPCS Drug Indicator                                        0
Number of Services                                          0
Number of Medicare Beneficiaries                            0
Number of Distinct Medicare Beneficiary/Per Day Services    0
Average Medicare Allowed Amount                             0
Average Submitted Charge Amount                             0
Average Medicare Payment Amount                             0
Average Medicare Standardized Amount                        0
dtype: int64

In [232]:
# Step 2: Drop specified columns
DropColumn= ['index', 'National Provider Identifier', 
            'Last Name/Organization Name of the Provider', 
            'First Name of the Provider', 'Middle Initial of the Provider', 
            'Street Address 1 of the Provider', 'Zip Code of the Provider', 
            'HCPCS Code']
cleaned_df = cleaned_df.drop(columns=DropColumn)

In [234]:
# Convert all numerical columns to numeric, setting invalid parsing to NaN
numerical_columns = [
    'Number of Services', 'Number of Medicare Beneficiaries', 
    'Number of Distinct Medicare Beneficiary/Per Day Services', 
    'Average Medicare Allowed Amount', 'Average Submitted Charge Amount', 
    'Average Medicare Payment Amount', 'Average Medicare Standardized Amount'
]

for column in numerical_columns:
    # Convert to numeric and set invalid parsing as NaN
    cleaned_df[column] = pd.to_numeric(cleaned_df[column], errors='coerce')
# Display info to verify the changes
print("\nDataset Info After Converting Columns to Numeric:")
print(cleaned_df.info())

Dataset Info After Converting Columns to Numeric:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   Credentials of the Provider                               100000 non-null  object
 1   Gender of the Provider                                    100000 non-null  object
 2   Entity Type of the Provider                               100000 non-null  object
 3   City of the Provider                                      100000 non-null  object
 4   State Code of the Provider                                100000 non-null  object
 5   Country Code of the Provider                              100000 non-null  object
 6   Provider Type                                             100000 non-null  object
 7   Medicare Participation Indicator                          100000 non-null  object
 8   Place of Service                                          100000 non-null  object
 9   HCPCS Description                                         100000 non-null  object
 10  HCPCS Drug Indicator                                      100000 non-null  object
 11  Number of Services                                        97347 non-null   float64
 12  Number of Medicare Beneficiaries                          99595 non-null   float64
 13  Number of Distinct Medicare Beneficiary/Per Day Services  98500 non-null   float64
 14  Average Medicare Allowed Amount                           99255 non-null   float64
 15  Average Submitted Charge Amount                           93277 non-null   float64
 16  Average Medicare Payment Amount                           99534 non-null   float64
 17  Average Medicare Standardized Amount                      99530 non-null   float64
dtypes: float64(7), object(11)
memory usage: 13.7+ MB
None

In [238]:
print("\nRows of the cleaned DataFrame:")
cleaned_df

Rows of the cleaned DataFrame:

,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,City of the Provider,State Code of the Provider,Country Code of the Provider,Provider Type,Medicare Participation Indicator,Place of Service,HCPCS Description,HCPCS Drug Indicator,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount
0,M.D.,F,I,SAINT LOUIS,MO,US,Internal Medicine,Y,F,"Initial hospital inpatient care, typically 70 ...",N,27.0,24.0,27.0,200.587778,305.211111,157.262222,160.908889
1,M.D.,F,I,FAYETTEVILLE,NC,US,Obstetrics & Gynecology,Y,O,"Screening mammography, bilateral (2-view study...",N,175.0,175.0,175.0,123.730000,548.800000,118.830000,135.315257
2,DPM,M,I,NORTH HAVEN,CT,US,Podiatry,Y,O,"Established patient home visit, typically 25 m...",N,32.0,13.0,32.0,90.650000,155.000000,64.439688,60.595937
3,MD,M,I,KANSAS CITY,MO,US,Internal Medicine,Y,O,"Urinalysis, manual test",N,20.0,18.0,20.0,3.500000,5.000000,3.430000,3.430000
4,DO,M,I,JUPITER,FL,US,Internal Medicine,Y,O,Injection beneath the skin or into muscle for ...,N,33.0,24.0,31.0,26.520000,40.000000,19.539394,19.057576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PT,F,I,WILMINGTON,IL,US,Physical Therapist in Private Practice,Y,O,"Evaluation of physical therapy, typically 30 m...",N,20.0,20.0,20.0,85.372500,214.000000,60.725500,62.248500
99996,ARNP,F,I,REDMOND,OR,US,Nurse Practitioner,Y,O,Established patient office or other outpatient...,N,136.0,107.0,136.0,61.270000,144.051471,30.006176,37.040221
99997,M.D.,M,I,SAINT LOUIS,MO,US,Cardiology,Y,F,"Doppler ultrasound study of heart blood flow, ...",N,11.0,11.0,11.0,17.980000,109.545455,14.090000,14.620000
99998,MD,F,I,LARCHMONT,NY,US,Internal Medicine,Y,O,Administration of influenza virus vaccine,N,12.0,12.0,12.0,30.540000,65.000000,29.930000,25.320000
99999,MD,F,I,GREAT NECK,NY,US,Physical Therapist in Private Practice,Y,O,Therapeutic procedure to re-educate brain-to-n...,N,589.0,76.0,587.0,38.601053,46.867572,29.736876,25.912139

In [240]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler,StandardScaler,OneHotEncoder
from sklearn.pipeline import make_pipeline

In [242]:
# List of nominal columns
nominal_columns = ['Credentials of the Provider','Gender of the Provider','Entity Type of the Provider','City of the Provider','State Code of the Provider',
                   'Country Code of the Provider','Provider Type','Medicare Participation Indicator','Place of Service','HCPCS Description','HCPCS Drug Indicator']

# Loop through each nominal column
for col in nominal_columns:
    unique_count = cleaned_df[col].nunique()  # Get the number of unique values in the column
    print(f"Column '{col}' has {unique_count} unique values.")
    
    # If the column has more than 10 unique values, apply frequency encoding
    if unique_count > 10:
        print(f"Applying frequency encoding to column: {col}")
        freq_map = cleaned_df[col].value_counts().to_dict()  # Create a frequency map
        cleaned_df[col] = cleaned_df[col].map(freq_map)  # Map the frequency values to the column
    else:
        # Otherwise, apply one-hot encoding
        print(f"Applying one-hot encoding to column: {col}")
        one_hot = pd.get_dummies(cleaned_df[col], prefix=col)  # Create one-hot encoded columns
        cleaned_df = pd.concat([cleaned_df, one_hot], axis=1)  # Add the one-hot columns to the DataFrame
        cleaned_df.drop(columns=[col], inplace=True)  # Drop the original column

Column 'Credentials of the Provider' has 1854 unique values.
Applying frequency encoding to column: Credentials of the Provider
Column 'Gender of the Provider' has 2 unique values.
Applying one-hot encoding to column: Gender of the Provider
Column 'Entity Type of the Provider' has 2 unique values.
Applying one-hot encoding to column: Entity Type of the Provider
Column 'City of the Provider' has 5846 unique values.
Applying frequency encoding to column: City of the Provider
Column 'State Code of the Provider' has 58 unique values.
Applying frequency encoding to column: State Code of the Provider
Column 'Country Code of the Provider' has 4 unique values.
Applying one-hot encoding to column: Country Code of the Provider
Column 'Provider Type' has 90 unique values.
Applying frequency encoding to column: Provider Type
Column 'Medicare Participation Indicator' has 2 unique values.
Applying one-hot encoding to column: Medicare Participation Indicator
Column 'Place of Service' has 2 unique values.
Applying one-hot encoding to column: Place of Service
Column 'HCPCS Description' has 2455 unique values.
Applying frequency encoding to column: HCPCS Description
Column 'HCPCS Drug Indicator' has 2 unique values.
Applying one-hot encoding to column: HCPCS Drug Indicator

In [244]:
# Display the updated DataFrame info
print("\nThe updated DataFrame info")
print(cleaned_df.info())

The updated DataFrame info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 26 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   Credentials of the Provider                               100000 non-null  int64
 1   City of the Provider                                      100000 non-null  int64
 2   State Code of the Provider                                100000 non-null  int64
 3   Provider Type                                             100000 non-null  int64
 4   HCPCS Description                                         100000 non-null  int64
 5   Number of Services                                        97347 non-null   float64
 6   Number of Medicare Beneficiaries                          99595 non-null   float64
 7   Number of Distinct Medicare Beneficiary/Per Day Services  98500 non-null   float64
 8   Average Medicare Allowed Amount                           99255 non-null   float64
 9   Average Submitted Charge Amount                           93277 non-null   float64
 10  Average Medicare Payment Amount                           99534 non-null   float64
 11  Average Medicare Standardized Amount                      99530 non-null   float64
 12  Gender of the Provider_F                                  100000 non-null  bool
 13  Gender of the Provider_M                                  100000 non-null  bool
 14  Entity Type of the Provider_I                             100000 non-null  bool
 15  Entity Type of the Provider_O                             100000 non-null  bool
 16  Country Code of the Provider_DE                           100000 non-null  bool
 17  Country Code of the Provider_JP                           100000 non-null  bool
 18  Country Code of the Provider_TR                           100000 non-null  bool
 19  Country Code of the Provider_US                           100000 non-null  bool
 20  Medicare Participation Indicator_N                        100000 non-null  bool
 21  Medicare Participation Indicator_Y                        100000 non-null  bool
 22  Place of Service_F                                        100000 non-null  bool
 23  Place of Service_O                                        100000 non-null  bool
 24  HCPCS Drug Indicator_N                                    100000 non-null  bool
 25  HCPCS Drug Indicator_Y                                    100000 non-null  bool
dtypes: bool(14), float64(7), int64(5)
memory usage: 10.5 MB
None

In [246]:
# Fill missing values for numerical columns with their mean
cleaned_df.fillna(cleaned_df.mean(), inplace=True)

# Convert all boolean columns to integers (True = 1, False = 0)
boolean_columns = cleaned_df.select_dtypes(include='bool').columns  # Find all boolean columns

for col in boolean_columns:
    cleaned_df[col] = cleaned_df[col].astype(int)  # Convert boolean to integer (True -> 1, False -> 0)

# Display the updated DataFrame info after filling NaNs and converting booleans
print("\nUpdated DataFrame info after filling missing values and converting boolean columns to integers:")
print(cleaned_df.info())

Updated DataFrame info after filling missing values and converting boolean columns to integers:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 26 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   Credentials of the Provider                               100000 non-null  int64
 1   City of the Provider                                      100000 non-null  int64
 2   State Code of the Provider                                100000 non-null  int64
 3   Provider Type                                             100000 non-null  int64
 4   HCPCS Description                                         100000 non-null  int64
 5   Number of Services                                        100000 non-null  float64
 6   Number of Medicare Beneficiaries                          100000 non-null  float64
 7   Number of Distinct Medicare Beneficiary/Per Day Services  100000 non-null  float64
 8   Average Medicare Allowed Amount                           100000 non-null  float64
 9   Average Submitted Charge Amount                           100000 non-null  float64
 10  Average Medicare Payment Amount                           100000 non-null  float64
 11  Average Medicare Standardized Amount                      100000 non-null  float64
 12  Gender of the Provider_F                                  100000 non-null  int32
 13  Gender of the Provider_M                                  100000 non-null  int32
 14  Entity Type of the Provider_I                             100000 non-null  int32
 15  Entity Type of the Provider_O                             100000 non-null  int32
 16  Country Code of the Provider_DE                           100000 non-null  int32
 17  Country Code of the Provider_JP                           100000 non-null  int32
 18  Country Code of the Provider_TR                           100000 non-null  int32
 19  Country Code of the Provider_US                           100000 non-null  int32
 20  Medicare Participation Indicator_N                        100000 non-null  int32
 21  Medicare Participation Indicator_Y                        100000 non-null  int32
 22  Place of Service_F                                        100000 non-null  int32
 23  Place of Service_O                                        100000 non-null  int32
 24  HCPCS Drug Indicator_N                                    100000 non-null  int32
 25  HCPCS Drug Indicator_Y                                    100000 non-null  int32
dtypes: float64(7), int32(14), int64(5)
memory usage: 14.5 MB
None

In [248]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [252]:
# Define columns for Min-Max scaling and Standard scaling
min_max = ['Number of Services', 'Number of Medicare Beneficiaries', 'Number of Distinct Medicare Beneficiary/Per Day Services']
standard = ['Average Medicare Allowed Amount', 'Average Submitted Charge Amount', 'Average Medicare Payment Amount', 'Average Medicare Standardized Amount']

# Apply Min-Max Scaling and Standard Scaling directly
preprocessor = ColumnTransformer(
    transformers=[
        ('min_max', MinMaxScaler(), min_max),
        ('standard', StandardScaler(), standard)
    ], 
    remainder='passthrough',  # Leave other columns unchanged
    verbose_feature_names_out=False
)

In [254]:
# Transform the data
transformed_df = preprocessor.fit_transform(cleaned_df)

In [256]:
# Convert to pandas DataFrame
transformed_df = pd.DataFrame(transformed_df, columns=preprocessor.get_feature_names_out())

In [260]:
transformed_df

,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount,Credentials of the Provider,City of the Provider,State Code of the Provider,...,Country Code of the Provider_DE,Country Code of the Provider_JP,Country Code of the Provider_TR,Country Code of the Provider_US,Medicare Participation Indicator_N,Medicare Participation Indicator_Y,Place of Service_F,Place of Service_O,HCPCS Drug Indicator_N,HCPCS Drug Indicator_Y
0,0.016194,0.013158,0.016194,1.098226,0.621012,0.972452,1.003321,32757.0,500.0,1997.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
1,0.165992,0.165992,0.165992,0.352134,1.940981,0.549955,0.722789,32757.0,209.0,3725.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.021255,0.002024,0.021255,0.031012,-0.192958,-0.047975,-0.096209,1330.0,10.0,1403.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
3,0.009109,0.007085,0.009109,-0.814992,-1.005784,-0.718674,-0.722804,40083.0,317.0,1997.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
4,0.022267,0.013158,0.020243,-0.591527,-0.816125,-0.541578,-0.551510,2478.0,51.0,7263.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0.009109,0.009109,0.009109,-0.020219,0.126753,-0.088807,-0.078095,800.0,323.0,4073.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
99996,0.126518,0.097166,0.126518,-0.254193,-0.252286,-0.426514,-0.354403,463.0,14.0,1046.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
99997,0.000000,0.000000,0.000000,-0.674428,-0.439269,-0.601485,-0.600151,32757.0,500.0,1997.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
99998,0.001012,0.001012,0.001012,-0.552503,-0.680654,-0.427351,-0.482868,40083.0,6.0,6361.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
99999,0.585020,0.065789,0.582996,-0.474250,-0.778910,-0.429474,-0.476378,40083.0,69.0,6361.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0

In [258]:
# Show transformed DataFrame
print(transformed_df.head())

   Number of Services  Number of Medicare Beneficiaries  \
0            0.016194                          0.013158
1            0.165992                          0.165992
2            0.021255                          0.002024
3            0.009109                          0.007085
4            0.022267                          0.013158

   Number of Distinct Medicare Beneficiary/Per Day Services  \
0                                           0.016194
1                                           0.165992
2                                           0.021255
3                                           0.009109
4                                           0.020243

   Average Medicare Allowed Amount  Average Submitted Charge Amount  \
0                         1.098226                         0.621012
1                         0.352134                         1.940981
2                         0.031012                        -0.192958
3                        -0.814992                        -1.005784
4                        -0.591527                        -0.816125

   Average Medicare Payment Amount  Average Medicare Standardized Amount  \
0                         0.972452                              1.003321
1                         0.549955                              0.722789
2                        -0.047975                             -0.096209
3                        -0.718674                             -0.722804
4                        -0.541578                             -0.551510

   Credentials of the Provider  City of the Provider  \
0                      32757.0                 500.0
1                      32757.0                 209.0
2                       1330.0                  10.0
3                      40083.0                 317.0
4                       2478.0                  51.0

   State Code of the Provider  ...  Country Code of the Provider_DE  \
0                      1997.0  ...                              0.0
1                      3725.0  ...                              0.0
2                      1403.0  ...                              0.0
3                      1997.0  ...                              0.0
4                      7263.0  ...                              0.0

   Country Code of the Provider_JP  Country Code of the Provider_TR  \
0                              0.0                              0.0
1                              0.0                              0.0
2                              0.0                              0.0
3                              0.0                              0.0
4                              0.0                              0.0

   Country Code of the Provider_US  Medicare Participation Indicator_N  \
0                              1.0                                 0.0
1                              1.0                                 0.0
2                              1.0                                 0.0
3                              1.0                                 0.0
4                              1.0                                 0.0

   Medicare Participation Indicator_Y  Place of Service_F  Place of Service_O  \
0                                 1.0                 1.0                 0.0
1                                 1.0                 0.0                 1.0
2                                 1.0                 0.0                 1.0
3                                 1.0                 0.0                 1.0
4                                 1.0                 0.0                 1.0

   HCPCS Drug Indicator_N  HCPCS Drug Indicator_Y
0                     1.0                     0.0
1                     1.0                     0.0
2                     1.0                     0.0
3                     1.0                     0.0
4                     1.0                     0.0

[5 rows x 26 columns]