In [16]:
import pandas as pd 
import numpy as np
from sklearn.compose import ColumnTransformer  
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder 
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split

In [2]:
dataset = pd.read_csv(r"C:\Users\PRIYANSHI\Desktop\MediAlert\Healthcare Providers.csv")

In [3]:
df_copy = dataset.copy()

In [4]:
df_copy.columns

Index(['index', 'National Provider Identifier',
       'Last Name/Organization Name of the Provider',
       'First Name of the Provider', 'Middle Initial of the Provider',
       'Credentials of the Provider', 'Gender of the Provider',
       'Entity Type of the Provider', 'Street Address 1 of the Provider',
       'Street Address 2 of the Provider', 'City of the Provider',
       'Zip Code of the Provider', 'State Code of the Provider',
       'Country Code of the Provider', 'Provider Type',
       'Medicare Participation Indicator', 'Place of Service', 'HCPCS Code',
       'HCPCS Description', 'HCPCS Drug Indicator', 'Number of Services',
       'Number of Medicare Beneficiaries',
       'Number of Distinct Medicare Beneficiary/Per Day Services',
       'Average Medicare Allowed Amount', 'Average Submitted Charge Amount',
       'Average Medicare Payment Amount',
       'Average Medicare Standardized Amount'],
      dtype='object')

In [5]:
df_copy.head(5)

,index,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,...,HCPCS Code,HCPCS Description,HCPCS Drug Indicator,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount
0,8774979,1891106191,UPADHYAYULA,SATYASREE,NaN,M.D.,F,I,1402 S GRAND BLVD,FDT 14TH FLOOR,...,99223,"Initial hospital inpatient care, typically 70 ...",N,27,24,27,200.58777778,305.21111111,157.26222222,160.90888889
1,3354385,1346202256,JONES,WENDY,P,M.D.,F,I,2950 VILLAGE DR,NaN,...,G0202,"Screening mammography, bilateral (2-view study...",N,175,175,175,123.73,548.8,118.83,135.31525714
2,3001884,1306820956,DUROCHER,RICHARD,W,DPM,M,I,20 WASHINGTON AVE,STE 212,...,99348,"Established patient home visit, typically 25 m...",N,32,13,32,90.65,155,64.4396875,60.5959375
3,7594822,1770523540,FULLARD,JASPER,NaN,MD,M,I,5746 N BROADWAY ST,NaN,...,81002,"Urinalysis, manual test",N,20,18,20,3.5,5,3.43,3.43
4,746159,1073627758,PERROTTI,ANTHONY,E,DO,M,I,875 MILITARY TRL,SUITE 200,...,96372,Injection beneath the skin or into muscle for ...,N,33,24,31,26.52,40,19.539393939,19.057575758

In [6]:
df_copy.describe()

              index  National Provider Identifier  Zip Code of the Provider
count  1.000000e+05                  1.000000e+05              1.000000e+05
mean   4.907646e+06                  1.498227e+09              4.163820e+08
std    2.839633e+06                  2.874125e+08              3.082566e+08
min    2.090000e+02                  1.003001e+09              6.010000e+02
25%    2.458791e+06                  1.245669e+09              1.426300e+08
50%    4.901266e+06                  1.497847e+09              3.633025e+08
75%    7.349450e+06                  1.740374e+09              6.819881e+08
max    9.847440e+06                  1.993000e+09              9.990166e+08

In [7]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   index                                                     100000 non-null  int64
 1   National Provider Identifier                              100000 non-null  int64
 2   Last Name/Organization Name of the Provider               100000 non-null  object
 3   First Name of the Provider                                95745 non-null   object
 4   Middle Initial of the Provider                            70669 non-null   object
 5   Credentials of the Provider                               92791 non-null   object
 6   Gender of the Provider                                    95746 non-null   object
 7   Entity Type of the Provider                               100000 non-null  object
 8   Street Address 1 of the Provider                          100000 non-null  object
 9   Street Address 2 of the Provider                          40637 non-null   object
 10  City of the Provider                                      100000 non-null  object
 11  Zip Code of the Provider                                  100000 non-null  float64
 12  State Code of the Provider                                100000 non-null  object
 13  Country Code of the Provider                              100000 non-null  object
 14  Provider Type                                             100000 non-null  object
 15  Medicare Participation Indicator                          100000 non-null  object
 16  Place of Service                                          100000 non-null  object
 17  HCPCS Code                                                100000 non-null  object
 18  HCPCS Description                                         100000 non-null  object
 19  HCPCS Drug Indicator                                      100000 non-null  object
 20  Number of Services                                        100000 non-null  object
 21  Number of Medicare Beneficiaries                          100000 non-null  object
 22  Number of Distinct Medicare Beneficiary/Per Day Services  100000 non-null  object
 23  Average Medicare Allowed Amount                           100000 non-null  object
 24  Average Submitted Charge Amount                           100000 non-null  object
 25  Average Medicare Payment Amount                           100000 non-null  object
 26  Average Medicare Standardized Amount                      100000 non-null  object
dtypes: float64(1), int64(2), object(24)
memory usage: 20.6+ MB

In [8]:
columns_numerical = [
    'Number of Services', 
    'Number of Medicare Beneficiaries', 
    'Number of Distinct Medicare Beneficiary/Per Day Services',
    'Average Medicare Allowed Amount', 
    'Average Submitted Charge Amount',  
    'Average Medicare Payment Amount',  
    'Average Medicare Standardized Amount' 
]

for column in columns_numerical:
    df_copy[column] = pd.to_numeric(df_copy[column], errors='coerce')

print("Data types after conversion:")
print(df_copy[columns_numerical].info())

Data types after conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Number of Services                                        97347 non-null  float64
 1   Number of Medicare Beneficiaries                          99595 non-null  float64
 2   Number of Distinct Medicare Beneficiary/Per Day Services  98500 non-null  float64
 3   Average Medicare Allowed Amount                           99255 non-null  float64
 4   Average Submitted Charge Amount                           93277 non-null  float64
 5   Average Medicare Payment Amount                           99534 non-null  float64
 6   Average Medicare Standardized Amount                      99530 non-null  float64
dtypes: float64(7)
memory usage: 5.3 MB
None

In [9]:
df_copy.isnull().sum()

index                                                           0
National Provider Identifier                                    0
Last Name/Organization Name of the Provider                     0
First Name of the Provider                                   4255
Middle Initial of the Provider                              29331
Credentials of the Provider                                  7209
Gender of the Provider                                       4254
Entity Type of the Provider                                     0
Street Address 1 of the Provider                                0
Street Address 2 of the Provider                            59363
City of the Provider                                            0
Zip Code of the Provider                                        0
State Code of the Provider                                      0
Country Code of the Provider                                    0
Provider Type                                                   0
Medicare Participation Indicator                                0
Place of Service                                                0
HCPCS Code                                                      0
HCPCS Description                                               0
HCPCS Drug Indicator                                            0
Number of Services                                           2653
Number of Medicare Beneficiaries                              405
Number of Distinct Medicare Beneficiary/Per Day Services     1500
Average Medicare Allowed Amount                               745
Average Submitted Charge Amount                              6723
Average Medicare Payment Amount                               466
Average Medicare Standardized Amount                          470
dtype: int64

In [10]:
DropCols = ['index', 'National Provider Identifier',
       'Last Name/Organization Name of the Provider',
       'First Name of the Provider', 'Middle Initial of the Provider','Street Address 1 of the Provider',
       'Street Address 2 of the Provider','Zip Code of the Provider',"HCPCS Code"]

In [11]:
df_copy.drop(columns=DropCols,inplace=True)

In [12]:
nominal_columns = [
    'Credentials of the Provider', 'Gender of the Provider', 'Entity Type of the Provider', 
    'City of the Provider', 'State Code of the Provider', 'Country Code of the Provider', 
    'Provider Type', 'Medicare Participation Indicator', 'Place of Service', 
    'HCPCS Description', 'HCPCS Drug Indicator'
]

for col in nominal_columns:
    unique_count = df_copy[col].nunique()
    print(f"Column '{col}' has {unique_count} unique values.")
    
    if unique_count > 10:
        print(f"Applying frequency encoding to column: {col}")
        freq_map = df_copy[col].value_counts().to_dict()
        df_copy[col] = df_copy[col].map(freq_map)
    else:
        print(f"Applying one-hot encoding to column: {col}")
        one_hot = pd.get_dummies(df_copy[col], prefix=col)
        df_copy = pd.concat([df_copy, one_hot], axis=1)
        df_copy.drop(columns=[col], inplace=True)

Column 'Credentials of the Provider' has 1854 unique values.
Applying frequency encoding to column: Credentials of the Provider
Column 'Gender of the Provider' has 2 unique values.
Applying one-hot encoding to column: Gender of the Provider
Column 'Entity Type of the Provider' has 2 unique values.
Applying one-hot encoding to column: Entity Type of the Provider
Column 'City of the Provider' has 5846 unique values.
Applying frequency encoding to column: City of the Provider
Column 'State Code of the Provider' has 58 unique values.
Applying frequency encoding to column: State Code of the Provider
Column 'Country Code of the Provider' has 4 unique values.
Applying one-hot encoding to column: Country Code of the Provider
Column 'Provider Type' has 90 unique values.
Applying frequency encoding to column: Provider Type
Column 'Medicare Participation Indicator' has 2 unique values.
Applying one-hot encoding to column: Medicare Participation Indicator
Column 'Place of Service' has 2 unique values.
Applying one-hot encoding to column: Place of Service
Column 'HCPCS Description' has 2455 unique values.
Applying frequency encoding to column: HCPCS Description
Column 'HCPCS Drug Indicator' has 2 unique values.
Applying one-hot encoding to column: HCPCS Drug Indicator

In [14]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 26 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   Credentials of the Provider                               92791 non-null   float64
 1   City of the Provider                                      100000 non-null  int64
 2   State Code of the Provider                                100000 non-null  int64
 3   Provider Type                                             100000 non-null  int64
 4   HCPCS Description                                         100000 non-null  int64
 5   Number of Services                                        97347 non-null   float64
 6   Number of Medicare Beneficiaries                          99595 non-null   float64
 7   Number of Distinct Medicare Beneficiary/Per Day Services  98500 non-null   float64
 8   Average Medicare Allowed Amount                           99255 non-null   float64
 9   Average Submitted Charge Amount                           93277 non-null   float64
 10  Average Medicare Payment Amount                           99534 non-null   float64
 11  Average Medicare Standardized Amount                      99530 non-null   float64
 12  Gender of the Provider_F                                  100000 non-null  bool
 13  Gender of the Provider_M                                  100000 non-null  bool
 14  Entity Type of the Provider_I                             100000 non-null  bool
 15  Entity Type of the Provider_O                             100000 non-null  bool
 16  Country Code of the Provider_DE                           100000 non-null  bool
 17  Country Code of the Provider_JP                           100000 non-null  bool
 18  Country Code of the Provider_TR                           100000 non-null  bool
 19  Country Code of the Provider_US                           100000 non-null  bool
 20  Medicare Participation Indicator_N                        100000 non-null  bool
 21  Medicare Participation Indicator_Y                        100000 non-null  bool
 22  Place of Service_F                                        100000 non-null  bool
 23  Place of Service_O                                        100000 non-null  bool
 24  HCPCS Drug Indicator_N                                    100000 non-null  bool
 25  HCPCS Drug Indicator_Y                                    100000 non-null  bool
dtypes: bool(14), float64(8), int64(4)
memory usage: 10.5 MB

In [15]:
df_copy.fillna(df_copy.mean(), inplace=True)

boolean_columns = df_copy.select_dtypes(include='bool').columns

for col in boolean_columns:
    df_copy[col] = df_copy[col].astype(int)

print("\nUpdated DataFrame info after filling missing values and converting boolean columns to integers:")
print(df_copy.info())

Updated DataFrame info after filling missing values and converting boolean columns to integers:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 26 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   Credentials of the Provider                               100000 non-null  float64
 1   City of the Provider                                      100000 non-null  int64
 2   State Code of the Provider                                100000 non-null  int64
 3   Provider Type                                             100000 non-null  int64
 4   HCPCS Description                                         100000 non-null  int64
 5   Number of Services                                        100000 non-null  float64
 6   Number of Medicare Beneficiaries                          100000 non-null  float64
 7   Number of Distinct Medicare Beneficiary/Per Day Services  100000 non-null  float64
 8   Average Medicare Allowed Amount                           100000 non-null  float64
 9   Average Submitted Charge Amount                           100000 non-null  float64
 10  Average Medicare Payment Amount                           100000 non-null  float64
 11  Average Medicare Standardized Amount                      100000 non-null  float64
 12  Gender of the Provider_F                                  100000 non-null  int32
 13  Gender of the Provider_M                                  100000 non-null  int32
 14  Entity Type of the Provider_I                             100000 non-null  int32
 15  Entity Type of the Provider_O                             100000 non-null  int32
 16  Country Code of the Provider_DE                           100000 non-null  int32
 17  Country Code of the Provider_JP                           100000 non-null  int32
 18  Country Code of the Provider_TR                           100000 non-null  int32
 19  Country Code of the Provider_US                           100000 non-null  int32
 20  Medicare Participation Indicator_N                        100000 non-null  int32
 21  Medicare Participation Indicator_Y                        100000 non-null  int32
 22  Place of Service_F                                        100000 non-null  int32
 23  Place of Service_O                                        100000 non-null  int32
 24  HCPCS Drug Indicator_N                                    100000 non-null  int32
 25  HCPCS Drug Indicator_Y                                    100000 non-null  int32
dtypes: float64(8), int32(14), int64(4)
memory usage: 14.5 MB
None

In [17]:
min_max = ['Number of Services', 'Number of Medicare Beneficiaries', 'Number of Distinct Medicare Beneficiary/Per Day Services']
standard = ['Average Medicare Allowed Amount', 'Average Submitted Charge Amount', 'Average Medicare Payment Amount', 'Average Medicare Standardized Amount']

preprocessor = ColumnTransformer(
    transformers=[
        ('min_max', MinMaxScaler(), min_max),
        ('standard', StandardScaler(), standard)
    ],
    remainder='passthrough',
    verbose_feature_names_out=False
)

In [19]:
transformed_df = preprocessor.fit_transform(df_copy)

In [20]:
transformed_df = pd.DataFrame(transformed_df, columns=preprocessor.get_feature_names_out())

In [21]:

transformed_df

,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount,Credentials of the Provider,City of the Provider,State Code of the Provider,...,Country Code of the Provider_DE,Country Code of the Provider_JP,Country Code of the Provider_TR,Country Code of the Provider_US,Medicare Participation Indicator_N,Medicare Participation Indicator_Y,Place of Service_F,Place of Service_O,HCPCS Drug Indicator_N,HCPCS Drug Indicator_Y
0,0.016194,0.013158,0.016194,1.098226,0.621012,0.972452,1.003321,32757.000000,500.0,1997.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
1,0.165992,0.165992,0.165992,0.352134,1.940981,0.549955,0.722789,32757.000000,209.0,3725.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.021255,0.002024,0.021255,0.031012,-0.192958,-0.047975,-0.096209,1330.000000,10.0,1403.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
3,0.009109,0.007085,0.009109,-0.814992,-1.005784,-0.718674,-0.722804,32874.000000,317.0,1997.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
4,0.022267,0.013158,0.020243,-0.591527,-0.816125,-0.541578,-0.551510,2478.000000,51.0,7263.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0.009109,0.009109,0.009109,-0.020219,0.126753,-0.088807,-0.078095,800.000000,323.0,4073.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
99996,0.126518,0.097166,0.126518,-0.254193,-0.252286,-0.426514,-0.354403,463.000000,14.0,1046.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
99997,0.000000,0.000000,0.000000,-0.674428,-0.439269,-0.601485,-0.600151,32757.000000,500.0,1997.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
99998,0.001012,0.001012,0.001012,-0.552503,-0.680654,-0.427351,-0.482868,23550.136252,6.0,6361.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
99999,0.585020,0.065789,0.582996,-0.474250,-0.778910,-0.429474,-0.476378,23550.136252,69.0,6361.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0

In [23]:
transformed_df.head()

,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount,Credentials of the Provider,City of the Provider,State Code of the Provider,...,Country Code of the Provider_DE,Country Code of the Provider_JP,Country Code of the Provider_TR,Country Code of the Provider_US,Medicare Participation Indicator_N,Medicare Participation Indicator_Y,Place of Service_F,Place of Service_O,HCPCS Drug Indicator_N,HCPCS Drug Indicator_Y
0,0.016194,0.013158,0.016194,1.098226,0.621012,0.972452,1.003321,32757.0,500.0,1997.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
1,0.165992,0.165992,0.165992,0.352134,1.940981,0.549955,0.722789,32757.0,209.0,3725.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.021255,0.002024,0.021255,0.031012,-0.192958,-0.047975,-0.096209,1330.0,10.0,1403.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
3,0.009109,0.007085,0.009109,-0.814992,-1.005784,-0.718674,-0.722804,32874.0,317.0,1997.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
4,0.022267,0.013158,0.020243,-0.591527,-0.816125,-0.541578,-0.551510,2478.0,51.0,7263.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0

In [24]:
#df.to_csv('Processed_dataset.csv')